name: aplikasi_kost
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  image_picker: ^1.0.7
  firebase_storage: ^12.1.0
  fl_chart: ^0.66.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  cloudinary_public: 0.23.1
  http: ^1.6.0
  googleapis_auth: ^1.4.1
  
  # --- DEPENDENSI TAMBAHAN UNTUK NOTIFIKASI ---
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^20.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Package untuk otomatis membuat ikon Android dan iOS
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# Konfigurasi Ikon Aplikasi
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # Support untuk android versi lama hingga baru
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

# The following section is specific to Flutter packages.
flutter:

  # Memastikan Material Icons tersedia
  uses-material-design: true

  # Mendaftarkan folder assets agar logo Anda bisa dibaca sistem
  assets:
    - assets/images/logo.png
    - assets/images/
    - aplikasi-kost-ea478-firebase-adminsdk-fbsvc-c88db29a39.json

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section.